// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PMS.API.Data;

#nullable disable

namespace PMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PMS.API.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("PMS.API.Models.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 24, 23, 21, 50, 463, DateTimeKind.Utc).AddTicks(9256),
                            Name = "Civil Engineer",
                            UpdatedAt = new DateTime(2026, 6, 24, 23, 21, 50, 463, DateTimeKind.Utc).AddTicks(9258)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 24, 23, 21, 50, 463, DateTimeKind.Utc).AddTicks(9264),
                            Name = "Structural Designer",
                            UpdatedAt = new DateTime(2026, 6, 24, 23, 21, 50, 463, DateTimeKind.Utc).AddTicks(9264)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 24, 23, 21, 50, 463, DateTimeKind.Utc).AddTicks(9265),
                            Name = "Project Coordinator",
                            UpdatedAt = new DateTime(2026, 6, 24, 23, 21, 50, 463, DateTimeKind.Utc).AddTicks(9266)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 24, 23, 21, 50, 463, DateTimeKind.Utc).AddTicks(9267),
                            Name = "Site Supervisor",
                            UpdatedAt = new DateTime(2026, 6, 24, 23, 21, 50, 463, DateTimeKind.Utc).AddTicks(9267)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 24, 23, 21, 50, 463, DateTimeKind.Utc).AddTicks(9268),
                            Name = "Electrical Engineer",
                            UpdatedAt = new DateTime(2026, 6, 24, 23, 21, 50, 463, DateTimeKind.Utc).AddTicks(9268)
                        });
                });

            modelBuilder.Entity("PMS.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PMS.API.Models.EmployeeDiscipline", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.HasKey("EmployeeId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("EmployeeDisciplines");
                });

            modelBuilder.Entity("PMS.API.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PMS.API.Models.ProjectDiscipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("FilledCount")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("ProjectId", "DisciplineId")
                        .IsUnique();

                    b.ToTable("ProjectDisciplines");
                });

            modelBuilder.Entity("PMS.API.Models.Assignment", b =>
                {
                    b.HasOne("PMS.API.Models.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.API.Models.Employee", "Employee")
                        .WithMany("Assignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.API.Models.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PMS.API.Models.EmployeeDiscipline", b =>
                {
                    b.HasOne("PMS.API.Models.Discipline", "Discipline")
                        .WithMany("EmployeeDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.API.Models.Employee", "Employee")
                        .WithMany("EmployeeDisciplines")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PMS.API.Models.ProjectDiscipline", b =>
                {
                    b.HasOne("PMS.API.Models.Discipline", "Discipline")
                        .WithMany("ProjectDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.API.Models.Project", "Project")
                        .WithMany("ProjectDisciplines")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PMS.API.Models.Discipline", b =>
                {
                    b.Navigation("EmployeeDisciplines");

                    b.Navigation("ProjectDisciplines");
                });

            modelBuilder.Entity("PMS.API.Models.Employee", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("EmployeeDisciplines");
                });

            modelBuilder.Entity("PMS.API.Models.Project", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ProjectDisciplines");
                });
#pragma warning restore 612, 618
        }
    }
}
